apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- postgres-statefulset.yml
- postgres-secret.enc.yml
- simple-todo-app-namespace.yml
- simple-todo-app-frontend-deployment.yml
- simple-todo-app-frontend-service.yml
- ingress.yml
images:
- name: SIMPLE_TODO_APP_FRONTEND_IMAGE
  newName: mickeckemi21/simple-todo-app-frontend
  newTag: fe785dc2fb5e1eceda96b286487bc4fa916ff367
