apiVersion: v1
kind: Service
metadata:
  namespace: simple-todo-app-namespace
  name: simple-todo-app-frontend-svc
spec:
  type: ClusterIP
  selector:
    app: simple-todo-app-frontend
  ports:
    - port: 8484
      protocol: TCP
      targetPort: 80