apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: simple-todo-app-namespace
  name: simple-todo-app-frontend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-todo-app-frontend
  template:
    metadata:
      labels:
        app: simple-todo-app-frontend
    spec:
      containers:
        - name: simple-todo-app-frontend
          image: SIMPLE_TODO_APP_FRONTEND_IMAGE
          resources:
            limits:
              cpu: "100m"
              memory: "15Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 10
