version: '3.1'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: simpletodo
      POSTGRES_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
  # docker run -p 4222:4222 -p 8222:8222 -p 6222:6222 --name nats-server -ti nats:latest
  nats-server:
    image: nats:2.6.5-alpine
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
