apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - simple-todo-app-frontend/manifests/deployment.yaml
  - simple-todo-app-frontend/manifests/service.yaml
images:
  - name: PROJECT/IMAGE-FRONTEND
    newName: gcr.io/PROJECT_ID/IMAGE
