name: GitOps Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'simple-todo-app/**'
      - '.github/workflows/gitops.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: simple-todo-app/simple-todo-app-frontend
          push: true
          tags: mickeckemi21/simple-todo-app-frontend:${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      # Set up kustomize
      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      # Update yamls
      - name: Update yamls
        working-directory: simple-todo-app/manifests
        run: |-
          kustomize edit set image SIMPLE_TODO_APP_FRONTEND_IMAGE=mickeckemi21/simple-todo-app-frontend:${{ github.sha }}

      # Commit and push
      - uses: EndBug/add-and-commit@v7
        with:
          add: 'simple-todo-app/manifests/kustomization.yml'
          message: New version release for gitops-app ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_API_TOKEN }}
