name: On branch DELETE

on:
  - delete
  
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-central2-b

jobs:
  clear-environment:
    name: Clear GKE Environment
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: $PROJECT_ID
          service_account_key: $GKE_KEY

      # Get the GKE credentials so we can deploy to the cluster
      - name: Set up GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      # Delete Environment (namespace) in GKE
      - name: Deploy
        run: |-
          kubectl delete namespace ${GITHUB_REF#refs/heads/}
